import { IConsultationReport } from '@/types/advisor-report';

const mockReports: IConsultationReport[] = [
  {
    id: 'rep-001',
    sessionId: 'ses-101',
    advisorId: 'adv-1',
    startupId: 'stu-1',
    startup: {
      id: 1,
      displayName: 'EcoVibe',
      logoUrl: null,
      industry: 'GreenTech',
      stage: 'Seed',
    },
    title: 'Báo cáo tư vấn Chiến lược GTM - EcoVibe',
    summary: 'Buổi tư vấn tập trung vào việc xác định phân khúc khách hàng mục tiêu và kênh tiếp cận ban đầu.',
    discussionOverview: 'Thảo luận về các rào cản khi tiếp cận thị trường B2B và cách tận dụng lợi thế cạnh tranh về bền vững.',
    keyFindings: 'Khách hàng mục tiêu đang tìm kiếm giải pháp tích hợp thay vì các sản phẩm đơn lẻ.',
    advisorRecommendations: 'Tập trung vào 3 khách hàng thử nghiệm lớn trong quý tới thay vì phân tán nguồn lực.',
    identifiedRisks: 'Chi phí vận hành ban đầu cao có thể làm chậm quá trình mở rộng.',
    nextSteps: 'Startup gửi bản kế hoạch chi tiết cho giai đoạn Pilot vào tuần sau.',
    deliverablesSummary: 'Bản checklist tiêu chí chọn đối tác chiến lược.',
    followUpRequired: true,
    followUpNotes: 'Cần kiểm tra lại tiến độ sau 2 tuần.',
    status: 'FINALIZED',
    version: 1,
    finalizedAt: '2026-03-20T10:00:00Z',
    lastEditedAt: '2026-03-20T10:00:00Z',
    history: [
      {
        id: 'hist-001',
        reportId: 'rep-001',
        version: 1,
        eventType: 'CREATED',
        actorType: 'ADVISOR',
        summary: 'Advisor khởi tạo báo cáo',
        createdAt: '2026-03-20T09:00:00Z',
      },
      {
        id: 'hist-002',
        reportId: 'rep-001',
        version: 1,
        eventType: 'FINALIZED',
        actorType: 'SYSTEM',
        summary: 'Báo cáo đã được phê duyệt và hoàn tất',
        createdAt: '2026-03-20T10:00:00Z',
      }
    ],
    attachments: [
      {
        id: 'att-001',
        reportId: 'rep-001',
        originalFileName: 'GTM_Checklist_v1.pdf',
        mimeType: 'application/pdf',
        fileSizeBytes: 1024000,
        attachmentType: 'DELIVERABLE',
        uploadedAt: '2026-03-20T09:45:00Z',
        url: '#',
      }
    ],
    sessionDate: '2026-03-18T14:00:00Z',
    sessionFormat: 'GOOGLE_MEET',
  },
  {
    id: 'rep-002',
    sessionId: 'ses-102',
    advisorId: 'adv-1',
    startupId: 'stu-2',
    startup: {
      id: 2,
      displayName: 'NovaAI',
      logoUrl: null,
      industry: 'AI/ML',
      stage: 'Series A',
    },
    title: 'Báo cáo tư vấn Vận hành - NovaAI',
    staffRemarks: "Vui lòng bổ sung thêm nội dung chi tiết về phần khuyến nghị kỹ thuật cho Startup.",
    summary: 'Đang soạn thảo dở nội dung buổi họp chiều nay.',
    discussionOverview: 'Trao đổi về hạ tầng GPU và tối ưu hóa chi phí cloud.',
    keyFindings: 'Chi phí AWS đang chiếm tỷ trọng quá lớn trong OPEX.',
    advisorRecommendations: 'Chuyển một phần workload sang Spot Instances.',
    identifiedRisks: 'Khả năng thiếu chip H100 trong quý tới.',
    nextSteps: 'Họp với bên cung cấp hạ tầng vào thứ 6.',
    deliverablesSummary: 'Tài liệu so sánh bảng giá các Cloud Provider.',
    followUpRequired: false,
    status: 'DRAFT',
    version: 1,
    lastEditedAt: '2026-03-22T15:00:00Z',
    history: [
      {
        id: 'hist-003',
        reportId: 'rep-002',
        version: 1,
        eventType: 'CREATED',
        actorType: 'ADVISOR',
        summary: 'Advisor khởi tạo báo cáo',
        createdAt: '2026-03-22T14:30:00Z',
      }
    ],
    attachments: [],
    sessionDate: '2026-03-22T14:00:00Z',
    sessionFormat: 'MICROSOFT_TEAMS',
  },
  {
    id: 'rep-003',
    sessionId: 'ses-002', // Linked to req-005
    advisorId: 'adv-1',
    startupId: '105',
    startup: {
      id: 105,
      displayName: 'CloudKitchen VN',
      industry: 'FoodTech',
      stage: 'Series B',
      logoUrl: null,
    },
    title: 'Báo cáo tư vấn Tài chính & Unit Economics - CloudKitchen VN',
    summary: 'Phân tích sâu về cấu trúc chi phí và lộ trình đạt điểm hòa vốn trước khi gọi vốn Series B.',
    discussionOverview: 'Thảo luận về tỷ lệ lãng phí nguyên liệu, chi phí marketing trên mỗi đơn hàng (CAC) và giá trị trọn đời khách hàng (LTV).',
    keyFindings: 'Tỷ lệ lãng phí tại các bếp trung tâm cao hơn 15% so với kế hoạch. CAC đang tăng nhẹ do cạnh tranh gay gắt.',
    advisorRecommendations: '- Triển khai hệ thống quản lý tồn kho thời gian thực.\n- Tối ưu hóa lộ trình giao hàng để giảm chi phí Logistics.\n- Tập trung vào các khách hàng doanh nghiệp (B2B) để tăng LTV.',
    identifiedRisks: 'Biến động giá nguyên liệu đầu vào và các đối thủ mới gia nhập thị trường.',
    nextSteps: 'Startup thực hiện audit kho bãi và gửi báo cáo tiến độ sau 4 tuần.',
    deliverablesSummary: 'File Excel mô hình tài chính dự báo 12 tháng tới.',
    followUpRequired: true,
    followUpNotes: 'Cần review lại sau khi Startup nộp audit kho bãi.',
    status: 'FINALIZED',
    version: 1,
    finalizedAt: '2026-03-10T09:00:00Z',
    lastEditedAt: '2026-03-10T09:00:00Z',
    history: [
      {
        id: 'hist-004',
        reportId: 'rep-003',
        version: 1,
        eventType: 'CREATED',
        actorType: 'ADVISOR',
        summary: 'Advisor khởi tạo báo cáo',
        createdAt: '2026-03-10T08:00:00Z',
      },
      {
        id: 'hist-005',
        reportId: 'rep-003',
        version: 1,
        eventType: 'FINALIZED',
        actorType: 'SYSTEM',
        summary: 'Báo cáo đã được phê duyệt',
        createdAt: '2026-03-10T09:00:00Z',
      }
    ],
    attachments: [
      {
        id: 'att-003',
        reportId: 'rep-003',
        originalFileName: 'Financial_Model_CloudKitchen.xlsx',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        fileSizeBytes: 2500000,
        attachmentType: 'DELIVERABLE',
        uploadedAt: '2026-03-10T08:30:00Z',
        url: '#',
      }
    ],
    sessionDate: '2026-03-08T14:00:00Z',
    sessionFormat: 'GOOGLE_MEET',
  }
];

export const getMockReports = () => mockReports;
export const getMockReportById = (id: string) => mockReports.find(r => r.id === id);
